### ISSUE TITLE
Integration with rust-geo/geo

### ISSUE THREAD

**Issue by kestred** [andelf/rust-postgis#11]
Greetings,

What are your thoughts on a possible feature-flag (or just straight use) that supports the crate https://github.com/georust/rust-geo for the rust-postgis extension?

In general, I like the design of the https://github.com/georust projects, because they use a single crate which defines the base geometric types and then have other projects to convert between specific formats (eg. https://github.com/georust/rust-geojson, https://github.com/georust/rust-wkt).

**Comment by pka** [comment]
Hi Kevin,
I probably had the same idea when I started the refactoring #9. But then I realized that the georust libraries are much less interoperable than I thought. I've opened georust/rust-geo#67 and currently Corey is working on a trait based implementation georust/rust-geo#85 of rust-geo. When this pull request is merged, we should have another look at integrating rust-postgis with geo-rust

**Comment by kestred** [comment]
Thanks for the quick feedback.  I'll track those issues.

**Comment by Farkal** [comment]
Any news on this ?

**Comment by pka** [comment]
Since rust-geo/geo 0.7.0 there is a postgis-integration feature flag. See also https://github.com/georust/geo/blob/master/geo/src/algorithm/from_postgis.rs
