### ISSUE TITLE
Support for postgis curve types?

### ISSUE THREAD

**Issue by fschutt** [andelf/rust-postgis#15]
Hi. Just wanted to ask - is there a way to get the geometry if the postgis geometry is a curve (such as `CURVEPOLYGON` and `CIRCULARSTRING`, etc.)?

**Comment by pka** [comment]
Almost 3 years after you asked, the answer is still the negative: there's no way for getting a curve geometry with rust-postgis apart from implementing the WKB parser and the WKB types for curves.
