### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by ajmurmann** [andelf/rust-postgis#7]
It would be very helpful to see a more complete example of how to use this. Especially on how to use this when writing geo data. I would happily do a PR, but unfortunately I don't understand enough about this library to contribute that at this point.

**Comment by andelf** [comment]
You're right. This repo lacks document & example.  :(
An obsoleted use case is at [andelf/rust-beijing-bus:src/main.rs](https://github.com/andelf/rust-beijing-bus/blob/master/src/main.rs)

TODO:
- [ ] Add Create/Insert/Update example

**Comment by pka** [comment]
Added basic crate documentation in 8c033ec
Time for a new release, @andelf ?

**Comment by andelf** [comment]
OK! I'll check it.

BTW, we have some ignored test cases. should we move to CircleCI which has a good backend db test env?

**Comment by andelf** [comment]
or to use a dockerized postgresql in travis-ci?

**Comment by andelf** [comment]
@pka will be published as v0.3.0 after I fix CI tests.

**Comment by pka** [comment]
The ignored tests should be run separately with cargo test --ignored (see README). This allows running the tests without PostGIS database. Setting up a PostGIS database on Travis shouldn't be a problem either.

**Comment by pka** [comment]
I see you're trying to install a newer PostGIS version in Travis. Doesn't the preinstalled PostGIS work for you? Shall we communicate by mail? My address is in the github profile.

**Comment by andelf** [comment]
Thanks. Done! 👍
I tried to update the default postgresql version. lol

**Comment by andelf** [comment]
@ajmurmann 
Shall we close this issue?

**Comment by pka** [comment]
I close this one with the improved README and the published API docs on https://docs.rs/postgis/
